apiVersion: apps/v1
kind: Deployment
metadata:
  name: qpu-gateway
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
        ports:
        - name: grpc
          containerPort: 50051
        env:
        - name: RIGETTI_API_KEY
          valueFrom:
            secretKeyRef:
              name: rigetti-creds
              key: apiKey
        - name: RIGETTI_API_SECRET
          valueFrom:
            secretKeyRef:
              name: rigetti-creds
              key: apiSecret
      - name: redis
        image: redis:7-alpine
        resources:
{{- toYaml .Values.redis.resources | nindent 10 }}
