name: Build & Sign Images

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - name: Login GHCR
      run: echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build gateway
      run: |
        docker buildx build --push \
          -t ghcr.io/arunsingh/qpu-gateway:${{ github.sha }} \
          -f gateways/qpu_gateway/Dockerfile \
          --platform linux/amd64,linux/arm64 .
    - name: SBOM
      uses: anchore/sbom-action@v0
      with:
        image: ghcr.io/arunsingh/qpu-gateway:${{ github.sha }}
    - name: Cosign sign
      run: |
        cosign sign --yes \
          --key ${{ secrets.COSIGN_KEY }} \
          ghcr.io/arunsingh/qpu-gateway:${{ github.sha }}

