name: Python Unit Tests

on:
  push:
    paths:
      - "oilandgas_qaoa/**"
      - "hft_qbm/**"
      - "policy_vqe/**"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: |
        pip install -e oilandgas_qaoa -e hft_qbm -e policy_vqe
        pytest -q
